recaptcha {
    // These keys are generated by the ReCaptcha service
    publicKey = "6Ldtp9ESAAAAALMQ38a5ajBZFf59xxGky-1aAawa"
    privateKey = "6Ldtp9ESAAAAAMJYTl_5ImAq0Ni8-LIhq9vKGdGN"

    // Include the noscript tags in the generated captcha
    includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
    development {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true

            // Communicate using HTTPS
            useSecureAPI = true
        }
    }
    production {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true

            // Communicate using HTTPS
            useSecureAPI = true
        }
    }
}